import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { SiteHeader } from "@/components/rootcode/SiteHeader";
import { SproutSpinner } from "@/components/rootcode/Sprout";
import { ProvenanceTimeline } from "@/components/rootcode/ProvenanceTimeline";
import { dataProvider, type Batch } from "@/lib/data";

export const Route = createFileRoute("/provenance/$batchId")({
  head: () => ({
    meta: [
      { title: "Batch Provenance — RootCode" },
      {
        name: "description",
        content:
          "Full provenance for an Ayurvedic herb batch: harvest photo, GPS origin, AI species verification, QC verdict and ledger hashes.",
      },
      { property: "og:title", content: "Batch Provenance — RootCode" },
      {
        property: "og:description",
        content: "Trace an Ayurvedic herb batch from soil to shelf.",
      },
    ],
  }),
  component: ProvenancePage,
});

// Alias for /trace/:batchId — the real backend's GET /api/qr returns:
//   "provenance_url": "https://herbtrace.rootcode.dev/provenance/<batchId>"
// so QR codes generated by the backend point to /provenance/..., not /trace/...
// Both routes render the same public (no-payment) view.
function ProvenancePage() {
  const { batchId } = Route.useParams();
  const [batch, setBatch] = useState<Batch | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    setLoading(true);
    dataProvider
      .getBatch(batchId)
      .then((b) => active && setBatch(b))
      .catch((e) => active && setError(e instanceof Error ? e.message : "Batch not found"))
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, [batchId]);

  return (
    <div className="min-h-screen">
      <SiteHeader />
      <main className="mx-auto w-full max-w-2xl px-4 py-8">
        {loading && <SproutSpinner label="Tracing batch…" />}

        {error && !loading && (
          <p className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
            {error}
          </p>
        )}

        {batch && !loading && (
          <ProvenanceTimeline batch={batch} showPaymentInfo={false} />
        )}
      </main>
    </div>
  );
}
