/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as ProvenanceBatchIdRouteImport } from './routes/provenance.$batchId'
import { Route as TraceBatchIdRouteImport } from './routes/trace.$batchId'
import { Route as HarvestStatusBatchIdRouteImport } from './routes/harvest.status.$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceBatchIdRoute = ProvenanceBatchIdRouteImport.update({
  id: '/provenance/$batchId',
  path: '/provenance/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceBatchIdRoute = TraceBatchIdRouteImport.update({
  id: '/trace/$batchId',
  path: '/trace/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestStatusBatchIdRoute = HarvestStatusBatchIdRouteImport.update({
  id: '/status/$batchId',
  path: '/status/$batchId',
  getParentRoute: () => HarvestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collect': typeof CollectRoute
  '/harvest': typeof HarvestRouteWithChildren
  '/provenance/$batchId': typeof ProvenanceBatchIdRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/harvest/status/$batchId': typeof HarvestStatusBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collect': typeof CollectRoute
  '/harvest': typeof HarvestRouteWithChildren
  '/provenance/$batchId': typeof ProvenanceBatchIdRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/harvest/status/$batchId': typeof HarvestStatusBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collect': typeof CollectRoute
  '/harvest': typeof HarvestRouteWithChildren
  '/provenance/$batchId': typeof ProvenanceBatchIdRoute
  '/trace/$batchId': typeof TraceBatchIdRoute
  '/harvest/status/$batchId': typeof HarvestStatusBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collect'
    | '/harvest'
    | '/provenance/$batchId'
    | '/trace/$batchId'
    | '/harvest/status/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/collect'
    | '/harvest'
    | '/provenance/$batchId'
    | '/trace/$batchId'
    | '/harvest/status/$batchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collect'
    | '/harvest'
    | '/provenance/$batchId'
    | '/trace/$batchId'
    | '/harvest/status/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CollectRoute: typeof CollectRoute
  HarvestRoute: typeof HarvestRouteWithChildren
  ProvenanceBatchIdRoute: typeof ProvenanceBatchIdRoute
  TraceBatchIdRoute: typeof TraceBatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance/$batchId': {
      id: '/provenance/$batchId'
      path: '/provenance/$batchId'
      fullPath: '/provenance/$batchId'
      preLoaderRoute: typeof ProvenanceBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$batchId': {
      id: '/trace/$batchId'
      path: '/trace/$batchId'
      fullPath: '/trace/$batchId'
      preLoaderRoute: typeof TraceBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest/status/$batchId': {
      id: '/harvest/status/$batchId'
      path: '/status/$batchId'
      fullPath: '/harvest/status/$batchId'
      preLoaderRoute: typeof HarvestStatusBatchIdRouteImport
      parentRoute: typeof HarvestRoute
    }
  }
}

interface HarvestRouteChildren {
  HarvestStatusBatchIdRoute: typeof HarvestStatusBatchIdRoute
}

const HarvestRouteChildren: HarvestRouteChildren = {
  HarvestStatusBatchIdRoute: HarvestStatusBatchIdRoute,
}

const HarvestRouteWithChildren =
  HarvestRoute._addFileChildren(HarvestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CollectRoute: CollectRoute,
  HarvestRoute: HarvestRouteWithChildren,
  ProvenanceBatchIdRoute: ProvenanceBatchIdRoute,
  TraceBatchIdRoute: TraceBatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
